burger: #namespace
    task_and_robot_environment_name: 'BurgerWarWorld-v0'

    #dqn parameters
    resume_epoch: "0"

    save_interval: 1
    epochs: 1000
    steps: 1000
    alpha: 1
    gamma: 64
    epsilon: 0.00025
    epsilon_discount: 1000000

    epsilon_decay: 0.995

    # maximum velocity
    vel_max_x: 0.22
    vel_min_x: 0.11
    vel_max_z: 0.785398
