
burger_battle: #namespace
    task_and_robot_environment_name: 'BurgerWarWorldBattle-v0'

    #dqn parameters
    resume_epoch: "0"

    save_interval: 1
    epochs: 1000
    steps: 1000
    explorationRate: 1
    minibatch_size: 64
    learningRate: 0.00025
    discountFactor: 0.99
    memorySize: 1000000

    updateTargetNetwork: 10000
    learnStart: 64
    network_inputs: 370
    network_outputs: 20
    network_structure: [370,370]

    epsilon_decay: 0.995

    # maximum velocity
    vel_max_x: 0.22
    vel_min_x: 0.11
    vel_max_z: 0.785398