burger: #namespace
    task_and_robot_environment_name: 'BurgerWarWorld-v0'

    #dqn parameters
    resume_epoch: "0"

    save_interval: 1
    epochs: 1000
    steps: 1000
    explorationRate: 1
    minibatch_size: 64
    learningRate: 0.00025
    discountFactor: 0.99
    memorySize: 1000000

    updateTargetNetwork: 500
    learnStart: 64
    network_inputs: 194
    network_outputs: 10
    network_structure: [194,194]

    epsilon_decay: 0.996

    # maximum velocity
    vel_max_x: 0.22
    vel_min_x: 0.15
    vel_max_z: 0.785398
