burger: #namespace
    task_and_robot_environment_name: 'BurgerWarWorld-v0'

    #dqn parameters
    resume_epoch: "0"

    save_interval: 1
    epochs: 1000
    steps: 1000
    explorationRate: 1
    minibatch_size: 64
    learningRate: 0.00025
    discountFactor: 0.99
    memorySize: 1000000

    updateTargetNetwork: 10000
    learnStart: 0
    network_inputs: 116
    network_outputs: 5
    network_structure: [116,116]

    epsilon_decay: 0.997

    # maximum velocity
    vel_max_x: 0.22
    vel_min_x: 0.12
    vel_max_z: 0.785398
